[package]
name = "girg_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cust = { version = "0.2" }
generator_common = { path = "../generator_common" }
gpu_generator = { path = "../gpu_generator" }
cpu_generator = { path = "../cpu_generator" }
crossbeam-channel = "0.5.1"
tracing = "0.1"
tracing-subscriber = "0.2.0"
clap = { version = "3.0.0-rc.4", features = ["derive"] }
anyhow = "1.0.51"

once_cell = "1.9.0"
indicatif = "0.16.2"

csv = "1.1.6"

[dev-dependencies]
mur3 = "0.1.0"
rstest = "0.12.0"